# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "c wright photo"
subtitle: ""
author: "Corey Wright"
header:
 title: "photography"
 subtitle: "by c wright"
footer:
 name: ""
 bio: ""
